name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build samples
      run: |
        pushd samples
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
    - name: build OboeTester
      run: |
        pushd apps/OboeTester
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
    - name: build fxlab
      run: |
        pushd apps/fxlab
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
 
